type User @table {
  displayName: String!
  createdAt: Timestamp!
  email: String
  photoUrl: String
}

type Project @table {
  name: String!
  location: String!
  startDate: Date!
  currentStatus: String!
  createdAt: Timestamp!
  description: String
  estimatedCompletionDate: Date
  manager: User
}

type ProjectPhase @table {
  name: String!
  order: Int!
  createdAt: Timestamp!
  description: String
  startDate: Date
  endDate: Date
  project: Project
}

type StatusUpdate @table {
  status: String!
  updateDate: Date!
  createdAt: Timestamp!
  notes: String
  project: Project
}

type ResponsibleParty @table {
  name: String!
  role: String!
  createdAt: Timestamp!
  contactInfo: String
}

type ProjectResponsibleParty @table(key: ["project", "responsibleParty"]) {
  assignedAt: Timestamp!
  roleInProject: String
  project: Project!
  responsibleParty: ResponsibleParty!
}